### ISSUE TITLE
Issue 1 User can search stock

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/stock-watch#1]
## 💰 Motivation

Users can search their favorite stocks

## 🖼️ Wireframes

<img width="217" alt="Screen Shot 2021-09-20 at 5 58 02 PM" src="https://user-images.githubusercontent.com/39370528/134096648-5d34d58e-6a09-4e67-9a9a-37e323d2f403.png">
<img width="211" alt="Screen Shot 2021-09-20 at 5 57 45 PM" src="https://user-images.githubusercontent.com/39370528/134096653-190a1134-67c9-440c-bc95-96f3b86535be.png">
<img width="216" alt="Screen Shot 2021-09-20 at 5 57 29 PM" src="https://user-images.githubusercontent.com/39370528/134096655-87652dbf-e232-4028-b259-dd7505e99a45.png">
<img width="477" alt="Screen Shot 2021-09-20 at 5 56 55 PM" src="https://user-images.githubusercontent.com/39370528/134096656-34f2461f-37fa-4e43-90cf-ec873c95e3a4.png">
<img width="484" alt="Screen Shot 2021-09-20 at 5 56 43 PM" src="https://user-images.githubusercontent.com/39370528/134096658-17663afa-fce2-48c1-8318-e3142b045689.png">
<img width="661" alt="Screen Shot 2021-09-20 at 5 56 26 PM" src="https://user-images.githubusercontent.com/39370528/134096659-2887e864-b1c7-46a8-accf-f17486244c0e.png">
## ✅ Task List

- [x] Create Nav Bar
- [x] Add Search bar
- [x] add an event listener on the search button and search input text
- [x] call function with the string of search input text 
- [x] generate dom tree and add API result to it
- [x] dive unique id name to each result
- [x] get API data and show the data on html page
- [x] add an event listener on the parent of the search list
- [x] get every miniute data of specific stock
- [x] push open,close,high,low,date of API response into diffrent array
- [x] get max and min of array hign and low
- [x] display the result in html page
