### ISSUE TITLE
Issue-6 User can see full stock history 

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/stock-watch#11]
## ⚙️ Feature

> User can see profit-loss statements 

## 🖼️ Wireframes
<img width="883" alt="Screen Shot 2021-09-29 at 4 46 58 PM" src="https://user-images.githubusercontent.com/39370528/135363809-9e1d10af-bba1-4d89-a00f-9136e6b82247.png">
<img width="537" alt="Screen Shot 2021-09-29 at 4 46 38 PM" src="https://user-images.githubusercontent.com/39370528/135363812-3473dab6-7805-4d79-ac28-ca2fb2c37c1e.png">

## ✅ Task List
- [x] Create modal for showing stocks history in graph
- [x] get stocks data by calling API
- [x] Plot graph using retrieved data
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
