### ISSUE TITLE
Issue 3 user can add stock to watch list

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/stock-watch#3]
## ⚙️ Feature

> ##### User will able to add stock to watch list

## 🖼️ Wireframes
<img width="748" alt="Screen Shot 2021-09-22 at 11 57 58 AM" src="https://user-images.githubusercontent.com/39370528/134405468-7edd1c36-eb76-42e5-bad3-083035fc6c43.png">
<img width="504" alt="Screen Shot 2021-09-22 at 11 58 40 AM" src="https://user-images.githubusercontent.com/39370528/134405478-448607d6-7110-4e3d-a56f-363da7334b63.png">
<img width="507" alt="Screen Shot 2021-09-22 at 11 58 23 AM" src="https://user-images.githubusercontent.com/39370528/134405481-15544c33-dd7c-47ce-8e7f-5a725b3668ae.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add watchlist button to navbar
- [x] create view for watchlist
- [x] code dom creation function to generate a list of stocks added to the watchlist
- [x] create edit page for watchlist
- [x] create modal for deleting stock
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
