### ISSUE TITLE
Issue 4 user can add stock to portfolio 

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/stock-watch#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can add stocks to portfolio

## 🖼️ Wireframes

<img width="854" alt="Screen Shot 2021-09-24 at 10 01 00 AM" src="https://user-images.githubusercontent.com/39370528/134713782-885ffb87-fec4-41e1-88e3-66231f769faf.png">
<img width="521" alt="Screen Shot 2021-09-24 at 10 00 38 AM" src="https://user-images.githubusercontent.com/39370528/134713787-28f93e0d-926b-4adb-a58c-0249ae6ccfb6.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create dom for getting input on the portfolio page
- [x] Store data in data object for of user input
- [x] Create  portfolio list page
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
