### ISSUE TITLE
issue 5 Users can get P&L of there stocks

### ISSUE THREAD

**Issue by meetkpatel** [meetkpatel/stock-watch#5]
## ⚙️ Feature

> User can see profit-loss statements 

## 🖼️ Wireframes

<img width="890" alt="Screen Shot 2021-09-27 at 10 01 13 AM" src="https://user-images.githubusercontent.com/39370528/134953563-6702663e-c238-4d6d-9070-3dbf2bab2051.png">
<img width="893" alt="Screen Shot 2021-09-27 at 10 00 59 AM" src="https://user-images.githubusercontent.com/39370528/134953567-7f4bb6a1-6851-4be2-af07-38f0515542d8.png">
<img width="762" alt="Screen Shot 2021-09-27 at 10 00 30 AM" src="https://user-images.githubusercontent.com/39370528/134953572-bb35f24d-1a34-4836-bf77-7f2f8ba613bc.png">

## ✅ Task List
- [x] Add portfolio div to HTML file
- [x] update dom function 
- [x] create dom for edit page 
- [x] make delete feature working
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
